import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/partials/Navbar'
import Footer from '@/components/partials/Footer'
import Header from '@/components/partials/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body>
            <Header/>
              <main>
                {children}
              </main>
            <Footer/>
        </body>
    </html>
  )
}
